### ISSUE TITLE
handleFileRead: File not found - what I do bad?

### ISSUE THREAD

**Issue by proasnet** [AndresDuran53/zarus-network-controller#2]
Hello, I am trying your examples in this library.
I have uploaded example, I have uploaded data for htm
I am connected as 192.168.4.2 and I am trying web interface at 192.168.4.1 and in browser I am not have anything.
In serial monitor I see
```
[INFO_LOG]  | Setting RGB Value: 255255255
[INFO_LOG]  | Setting RGB Value: 000
[DEBUG_LOG] | handleFileRead: /
[DEBUG_LOG] | 	File Not Found
[DEBUG_LOG] | handleFileRead: /
[DEBUG_LOG] | 	File Not Found
[DEBUG_LOG] | handleFileRead: /
[DEBUG_LOG] | 	File Not Found
[DEBUG_LOG] | handleFileRead: /
[DEBUG_LOG] | 	File Not Found
[DEBUG_LOG] | handleFileRead: /
[DEBUG_LOG] | 	File Not Found

```
Thank you very much for help.

**Comment by AndresDuran53** [comment]
I have noticed that the ESP8266fs plugin mentioned in the documentation does not work with files uploaded using LittleFS. Therefore, I have updated the documentation to redirect to the esp8266littlefs plugin, which works seamlessly with ESP8266. However, I currently do not have an ESP32 to test it. Thanks for the issue and let me know if this fix your problem.

**Comment by proasnet** [comment]
Thank you. Its working fine.
